### PR TITLE
Add support for creating lines between markers

### PR DESCRIPTION
**Pull request by DRuggeri**
This PR adds support for drawing lines between markers that are defined on the map. The lines are drawn before the markers to ensure they do not cross "over" a marker. A sample is included to demonstrate the flight path @themustafaomar may take if he were to visit me :-)

NOTE:
This is my first time developing in a node.js environment - feedback is very much welcome. I tried to follow the conventions I learned in the code, but please let me know if anything is not correct. To help ease others who may be new to Node, I added some additional information to the README so they can bootstrap quickly.

### CODE REVIEW

**Comment by themustafaomar** [comment]
Thank you! this is an awesome feature 🎉 
Just see this now, I'm gonna do some tests to ensure everything works correctly, and we're ready to merge this.

Regards.

**Comment by themustafaomar** [comment]
WTH, I was doing a rebase to clean the history by removing some unwanted commits.

It looks like your branch tried to merge the commits that I've just already deleted in the master branch.
I'm so sorry about that, I was supposed to do the rebase after merging this 😞 

Could you please clone the repository and open a new PR with the same message and changes, I'd be appreciated!

Regards.

**Comment by DRuggeri** [comment]
No problem - I just cloned your repo again, applied the diff of my changes, and then force-pushed the history to my fork to overwrite it. PR should be good to go.

**Comment by themustafaomar** [comment]
Thanks!

**Comment by DRuggeri** [comment]
Great to see it merged. Should I open another PR to update the dist code, or is there a release process that is more appropriate for that?

**Comment by themustafaomar** [comment]
Actually, the Github repository's dist folder shouldn't be updated see #9 
I will publish a new version to npm very soon mostly this week.

**Pull request merged**
